// render/app/Application.vue
<template>
    <router-view/>
</template>

<script lang="ts">
    import Vue from "vue";
    import Component from "vue-class-component";
    import VueRouter from "vue-router";
    import routes from "./routes";
    import store from "./store/store";

    const router = new VueRouter({
        linkExactActiveClass: "is-active",
        linkActiveClass:      "",
        routes,
    });

    @Component<Application>({ name: "Application", router, store })
    export default class Application extends Vue {
        // Not much happens here.
    }
</script>

// render/app/Application.tsx
import VueRouter from "vue-router";
import * as tsx from "vue-tsx-support";
import routes from "./routes";
import store from "./store/store";

// @vue/component
const Application = tsx.component({
    name: "Application",
    render() {
        return (<router-view/>);
    },
    router: new VueRouter({
        linkExactActiveClass: "is-active",
        linkActiveClass:      "",
        routes,
    }),
    store,
});

type Application = InstanceType<typeof Application>;
export default Application;
